<?php // This file is protected by copyright law and provided under license. Reverse engineering of this file is strictly prohibited.




































































































$JKfIh62134479PrQBs=104020974;$YzaNx86375644zFwTc=324136577;$NiRnN24984647xPWWg=329903426;$DbTZh92328490hUdkr=7908711;$glyZP60546487XrQYI=925471295;$WCZvL42448958Gbgjl=656124434;$MOUgZ41798612lbgWL=340122520;$BJdzi49707434iqrEc=970886912;$RkUdy44151819DxGIG=267900260;$GLprU28288314DAsyL=436888497;$KytTR73748431TohUf=126408706;$uECoc67671307EfXLV=268891789;$UkxMX74464705SJhGN=585547210;$jEziC10081213SOkwi=298002660;$UVzcA69693026WhyQY=603320740;$YfigR29687200oKwTs=378045993;$yNati28164293jtsJC=63617979;$oopOJ50620888oaEXT=568039725;$jpVMg65540138TpQaJ=710494191;$OApxL15717597xlpbs=629352476;$eOtvV63751839lBsvh=656485346;$bbCtI68012193afGPG=797299651;$VFJGU12149213eXlHL=934992084;$qyaoY74310747aSEjH=350313497;$STQDV31741517oGxXM=64810244;$kvhST80316783nJPzs=603391413;$NHzIq35183848gCdaA=729334538;$hqyNL29387902Wviuo=767451718;$VsJTI11527712unUgf=878127399;$yXHkU34056537TfuDg=654063746;$LMiBU40543889pgmXA=696150937;$ZduDD15231708xJjqg=404908216;$gIXVi32347251IPLva=29621052;$iKuni99249635OrppL=574499996;$qfKsG13834029MSvjt=21198800;$SUUkR84386925OClkV=983167140;$dVjEF46629990hLrlo=799514144;$QgbAI26255616Tdjap=891318800;$ZDKtF25422633EGOiJ=934641715;$GjlYb56952810hzhuP=967168165;$HUqHR10214368bnQYF=255571077;$tbtJI38453807zkvpD=785462049;$OAYih23014595FUfQs=574181557;$nFaKI51938789YrkHE=556816064;$jvUXW29921692MtKUa=218045555;$KDhDa21694455Tkrpi=202730028;$XNMlX84523598CkzSu=899468140;$noqJH67570740qClSL=231328017;$hlYAz72138145PiKQq=940851589;$ZYfgt60537063sbild=606952717;?><?php class HTTPFetch { var $EcY5TE9M14WPJPp = array(); var $E7Y4UT6F3_5K = array(); var $Vm5v0DwY4sp = array(); var $dO4Qk6wY4 = 0; var $eFYRl87PNHf = 0; var $caxPgBJES6xJS3M3 = 0; var $xMUDKBqCk3SP5yBxECB = array(); var $Ckch2Ta5ev = array(); var $nettime = 0; var $ylHq2XW203CDYm1xpm = 0; var $JJjzIRLhzb6m = 0; var $_t1 = 0; var $_vertype = ''; var $udu_HMPcsk1WD = null; var $CjxnKeP8b = 0; var $q_fhUNBxplCNm_FZbwj = array(); var $gTpa7vImEYUYoL0h = array(); var $cnP9S98d8 = array(); function kmOVeYV7r() { include Y9kqmA8n8Eh.'page-generator.inc.php'; $this->_vertype = $lr3E_ME7FUinJ5S['version']; global $grab_parameters; if($_ic = $grab_parameters['xs_init_cookie']){ if($nEvZqW11Vdc = @json_decode($_ic,1)) { $Vmi4zgiBcYoQP = $this->mKyVS1wi4VQ(parse_url($grab_parameters['xs_initurl'])); $this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP] = $nEvZqW11Vdc; } } } function Qf7SBzxTcF_AAsL($mcGAs25_n6HbUaxC) { if (preg_match('#^([^/]*\://[^/]*)(\?.*)$#', $mcGAs25_n6HbUaxC, $um)) { 
																													 $mcGAs25_n6HbUaxC = $um[1] . '/' . $um[2]; } return $mcGAs25_n6HbUaxC; } function iwNQepY495NZsMCjyvY($ZR9ARCxDNGt){ return strstr($ZR9ARCxDNGt, 'text/') || strstr($ZR9ARCxDNGt, '/xhtml') || strstr($ZR9ARCxDNGt, '/pdf') || strstr($ZR9ARCxDNGt, '/json') || (uYtRST7eOVyiC('xs_parse_swf',false)&& strstr($ZR9ARCxDNGt, 'shockwave-flash') ) ; } function S69oU_Ht7vJryEPIweK($rYtZGoKYBfTszYC4ZFo = array()){ global $grab_parameters; if(!$this->dO4Qk6wY4) $this->dO4Qk6wY4 = $grab_parameters['xs_socket_timeout'] ? $grab_parameters['xs_socket_timeout'] : 30; $_tmout = isset($rYtZGoKYBfTszYC4ZFo['timeout']) ? $rYtZGoKYBfTszYC4ZFo['timeout'] : $this->dO4Qk6wY4; @ini_set('default_socket_timeout', $_tmout); return $_tmout; } function PCTbReMjLdqpDd($Wlp5TPASuidvTEC25u) { } function Gxwg3kTXjBlOBM4R($gkgJ3qKwv6xXo0IhLc) { return $this->fetch($gkgJ3qKwv6xXo0IhLc['url'], 0, $gkgJ3qKwv6xXo0IhLc['follow'], false, $gkgJ3qKwv6xXo0IhLc['htpost'], $gkgJ3qKwv6xXo0IhLc); } function AvxbGafLYgOj4BYC7($wn5ZmaRyt){ return false; } function PsiPUeBCQgzxKlY($wn5ZmaRyt) { $rr = array(); } function uQU9ttG_RWz_P8mgC0($oawGgHtKjDfNQptzC2, $vFPe3eY66rprDu2 = false) { global $grab_parameters; if (preg_match('#(.+):(.+)#', $grab_parameters['xs_curlproxy'], $pm)) { $grab_parameters['xs_ipconnection']   = $pm[1]; $grab_parameters['xs_portconnection'] = $pm[2]; } $xwrGlYGGtfdg3hwfM8Y = ($oawGgHtKjDfNQptzC2['scheme'] == 'https'); $hJnnJVG5lZbvkEqWmE  = $oawGgHtKjDfNQptzC2['path']; $_q       = isset($oawGgHtKjDfNQptzC2['query']) ? $oawGgHtKjDfNQptzC2['query'] : ''; if ($grab_parameters['xs_extra_param']) $_q .= ($_q ? '&' : '') . $grab_parameters['xs_extra_param']; if ($_q) $hJnnJVG5lZbvkEqWmE .= '?' . $_q; $hJnnJVG5lZbvkEqWmE = str_replace('&amp;', '&', $hJnnJVG5lZbvkEqWmE); $hJnnJVG5lZbvkEqWmE = str_replace(' ', '%20', $hJnnJVG5lZbvkEqWmE); $ZD3uVZVhYZ3   = 100; if ($grab_parameters['xs_utf8']) { $hJnnJVG5lZbvkEqWmE = EqBQXy6EAoy0Oy($hJnnJVG5lZbvkEqWmE); } if(!isset($this->E7Y4UT6F3_5K[$oawGgHtKjDfNQptzC2['host']])){ $this->E7Y4UT6F3_5K[$oawGgHtKjDfNQptzC2['host']] = gethostbyname($oawGgHtKjDfNQptzC2['host']); } $ixSD5NLpQneK = $oawGgHtKjDfNQptzC2['host']; return array( 'fullurl' => $oawGgHtKjDfNQptzC2['scheme'].'://'.$oawGgHtKjDfNQptzC2['host'] . $hJnnJVG5lZbvkEqWmE.($oawGgHtKjDfNQptzC2['fragment']?'#'.$oawGgHtKjDfNQptzC2['fragment']:''), 
																													 'hJnnJVG5lZbvkEqWmE' => $hJnnJVG5lZbvkEqWmE, 'xwrGlYGGtfdg3hwfM8Y' => $xwrGlYGGtfdg3hwfM8Y, 'jXqw1PaftKXckc_br' => (($xwrGlYGGtfdg3hwfM8Y && ($grab_parameters['xs_portconnection']!='80'))? 'ssl://' : '') . 
																													 (($grab_parameters['xs_ipconnection'] && !$vFPe3eY66rprDu2) ? $grab_parameters['xs_ipconnection'] : $ixSD5NLpQneK ), 'EyCtzkMDXqy'   => (($grab_parameters['xs_portconnection'] && !$vFPe3eY66rprDu2) ? $grab_parameters['xs_portconnection'] : (($oawGgHtKjDfNQptzC2['port'] && !$vFPe3eY66rprDu2) ? $oawGgHtKjDfNQptzC2['port'] : ($xwrGlYGGtfdg3hwfM8Y ? 443 : 80))) ); } function yOWUuvfw5LpNt($_ua = ''){ global $grab_parameters; return  $_ua ? $_ua : ($grab_parameters['xs_crawl_ident'] ? $grab_parameters['xs_crawl_ident'] : 'Mozilla/5.0 (compatible; XML Sitemaps Generator; http://www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0'); 
																													 } function EstmcxQXJ9yRpDRI4($mcGAs25_n6HbUaxC) { global $grab_parameters; if ($grab_parameters['xs_urlprefix']) { $mcGAs25_n6HbUaxC = $grab_parameters['xs_urlprefix'] . urlencode($mcGAs25_n6HbUaxC); } if ($grab_parameters['xs_inc_ajax'] && preg_match('#\#\!(.*)$#', $mcGAs25_n6HbUaxC, $um)) { $mcGAs25_n6HbUaxC = str_replace($um[0], (strstr($mcGAs25_n6HbUaxC, '?') ? '&' : '?') . '_escaped_fragment_=' . urlencode($um[1]), $mcGAs25_n6HbUaxC); } return $mcGAs25_n6HbUaxC; } function mKyVS1wi4VQ($oawGgHtKjDfNQptzC2){ preg_match("/([\-\w]+\.?\w+)$/", $oawGgHtKjDfNQptzC2['host'], $yz9iRuESaitPEgYSsu); return strtolower($yz9iRuESaitPEgYSsu[1]); } function fLvXqoro1CeRrvGa($oawGgHtKjDfNQptzC2){ global $grab_parameters; $Vmi4zgiBcYoQP    = $this->mKyVS1wi4VQ($oawGgHtKjDfNQptzC2); $fLvXqoro1CeRrvGa = ""; if(!$grab_parameters['xs_no_cookies']) if (isset($this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP]) && $this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP]) { foreach ($this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP] as $k => $v) $fLvXqoro1CeRrvGa .= ($fLvXqoro1CeRrvGa ? "; " : "") . "$k=$v"; } return $fLvXqoro1CeRrvGa; } function Mz_C1OZohEROPG3vGxh($hJnnJVG5lZbvkEqWmE, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo = array()){ global $grab_parameters; $cpteLwScbUb = $rYtZGoKYBfTszYC4ZFo['htpost']; $QtD2z5aBlIu8TRbTGd8 = $rYtZGoKYBfTszYC4ZFo['req'] ? $rYtZGoKYBfTszYC4ZFo['req'] : ($cpteLwScbUb ? "POST" : "GET"); $yEcu5BRNKMB63K = $QtD2z5aBlIu8TRbTGd8 . ' ' . $hJnnJVG5lZbvkEqWmE . " HTTP/1.1\r\n"; $yEcu5BRNKMB63K .= "Host: " . $oawGgHtKjDfNQptzC2['host'] . "\r\n"; $yEcu5BRNKMB63K .= "Referer: " . ($rYtZGoKYBfTszYC4ZFo['_ref'] ? $rYtZGoKYBfTszYC4ZFo['_ref'] : $oawGgHtKjDfNQptzC2['scheme']."://" . $oawGgHtKjDfNQptzC2['host'] . "/") . "\r\n"; 
																													 $yEcu5BRNKMB63K .= "User-Agent: " . $this->yOWUuvfw5LpNt($rYtZGoKYBfTszYC4ZFo['_ua']). "\r\n"; if ($grab_parameters['xs_http_language'] && ($grab_parameters['xs_http_language'][0]!='-')) $yEcu5BRNKMB63K .= "Accept-Language: ".$grab_parameters['xs_http_language']."\r\n"; if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']) $yEcu5BRNKMB63K .= "Accept-Encoding: gzip\r\n"; $_accept = trim($grab_parameters['xs_http_accept']); if($rYtZGoKYBfTszYC4ZFo['accept_more'] || !$_accept){ $_accept = "text/html,text/xml,application/xml,application/xhtml+xml". ($rYtZGoKYBfTszYC4ZFo['accept_more']?','.$rYtZGoKYBfTszYC4ZFo['accept_more']:''). ";q=0.9,text/plain;q=0.8,image/png,*"."/"."*;q=0.5"; } $yEcu5BRNKMB63K .= "Accept: $_accept\r\n"; if($_hh = trim($grab_parameters['xs_httpheaders'])){ $_ar = preg_split('#([\r\n]|(\\\\n))+#', $_hh); foreach($_ar as $niMEktmuz91vzUA5p){ list($v, $v2) = explode('|', $niMEktmuz91vzUA5p); if(strstr($v,':')) if(!$v2 || preg_match('#'.$v2.'#', $oawGgHtKjDfNQptzC2['host'].$hJnnJVG5lZbvkEqWmE)) $yEcu5BRNKMB63K .= trim($v)."\r\n"; } } if($rYtZGoKYBfTszYC4ZFo['addheaders']) $yEcu5BRNKMB63K .= $rYtZGoKYBfTszYC4ZFo['addheaders']; if ($cpteLwScbUb) { $yEcu5BRNKMB63K .= "Content-Type: ".($rYtZGoKYBfTszYC4ZFo['contenttype']?$rYtZGoKYBfTszYC4ZFo['contenttype']:'text/xml')."\r\n"; $yEcu5BRNKMB63K .= "Content-Length: " . strlen($cpteLwScbUb) . "\r\n"; } else { if(!$rYtZGoKYBfTszYC4ZFo['skip_cookies']) if ($fLvXqoro1CeRrvGa = $this->fLvXqoro1CeRrvGa($oawGgHtKjDfNQptzC2)) $yEcu5BRNKMB63K .= "Cookie: " . $fLvXqoro1CeRrvGa . "\r\n"; if ($grab_parameters['xs_keep_alive']) $yEcu5BRNKMB63K .= "Connection: Keep-Alive\r\n"; else $yEcu5BRNKMB63K .= "Connection: Close\r\n"; } $yEcu5BRNKMB63K .= "\r\n"; if ($cpteLwScbUb) $yEcu5BRNKMB63K .= $cpteLwScbUb; Gpa9Bjai2UMV7SSv($yEcu5BRNKMB63K, 3); return $yEcu5BRNKMB63K; } function O0gohaNXNBX(&$BPV0v0JW1mGrba_69IZ, $u7upMlonmIG9k5x36_5 = false, $rYtZGoKYBfTszYC4ZFo= array()){ global $grab_parameters, $hJQXILvfL; extract($BPV0v0JW1mGrba_69IZ); if ($jXqw1PaftKXckc_br) { if(!$this->_t1)$this->_t1 = microtime(true); $dkt0PfuKEtl5ZJSamX = null; $kjQRPmUNRCzHK5nPY = array( 'ssl' => array( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true ) ); if (!$hJQXILvfL) { $UILz8K3UFCA68 = stream_context_create($kjQRPmUNRCzHK5nPY); $BilpmnB9WWRbk = STREAM_CLIENT_CONNECT; $dkt0PfuKEtl5ZJSamX     = @stream_socket_client($jXqw1PaftKXckc_br . ':' . $EyCtzkMDXqy, $RQb6ylQQJOqbb_vw, $th9M5vSd8jZsHR9tvQ, 5, $BilpmnB9WWRbk, $UILz8K3UFCA68); } $nczJrhmuaDEqS = explode('|', trim($grab_parameters['xs_more_ips'])); if (!$dkt0PfuKEtl5ZJSamX && $nczJrhmuaDEqS && $nczJrhmuaDEqS[0] && function_exists('stream_context_create') && function_exists('stream_socket_client')) { if (!$hJQXILvfL) $hJQXILvfL = 1; while ($hJQXILvfL < count($nczJrhmuaDEqS)) { $kjQRPmUNRCzHK5nPY['so'.'cket'] = array( 'bindto' => $nczJrhmuaDEqS[$hJQXILvfL] . ':0' ); $UILz8K3UFCA68 = stream_context_create($kjQRPmUNRCzHK5nPY); $BilpmnB9WWRbk = STREAM_CLIENT_CONNECT|($u7upMlonmIG9k5x36_5?STREAM_CLIENT_ASYNC_CONNECT:0); $dkt0PfuKEtl5ZJSamX     = @stream_socket_client($jXqw1PaftKXckc_br . ':' . $EyCtzkMDXqy, $RQb6ylQQJOqbb_vw, $th9M5vSd8jZsHR9tvQ, 5, $BilpmnB9WWRbk, $UILz8K3UFCA68); if ($dkt0PfuKEtl5ZJSamX) break; $hJQXILvfL++; } if (!$dkt0PfuKEtl5ZJSamX) $hJQXILvfL = 0; } } if($dkt0PfuKEtl5ZJSamX){ @stream_set_timeout($dkt0PfuKEtl5ZJSamX, $this->S69oU_Ht7vJryEPIweK($rYtZGoKYBfTszYC4ZFo)); if(//count($this->Ckch2Ta5ev)>1 && 
																													 $u7upMlonmIG9k5x36_5 && function_exists('stream_set_blocking')){ @stream_set_blocking($dkt0PfuKEtl5ZJSamX, 0); } }else{ $BPV0v0JW1mGrba_69IZ['errormsg'] = 'Error opening socket to '.$jXqw1PaftKXckc_br.'<br />'.$th9M5vSd8jZsHR9tvQ; if (!$jXqw1PaftKXckc_br) $BPV0v0JW1mGrba_69IZ['aflags']['error'] = "incorrect url - $mcGAs25_n6HbUaxC"; else $BPV0v0JW1mGrba_69IZ['aflags']['socket_timeout'] = "connect - $jXqw1PaftKXckc_br - " . $oawGgHtKjDfNQptzC2['host'] . " - $EyCtzkMDXqy - $mcGAs25_n6HbUaxC"; } return $dkt0PfuKEtl5ZJSamX; } function ENpmVqlCIr4BDJ5dZR(){ $this->Ckch2Ta5ev = array(); $this->udu_HMPcsk1WD = null; } function j2VQsZg57Bu($i){ return $this->Ckch2Ta5ev[$i]; } function TzZwFXuNmmdAfory($mcGAs25_n6HbUaxC, $FCkdZaMLt59lOenI, $yEcu5BRNKMB63K, $rYtZGoKYBfTszYC4ZFo = array()){ $this->Ckch2Ta5ev[$mcGAs25_n6HbUaxC] = array_merge($rYtZGoKYBfTszYC4ZFo,array( 'CTbReMjLdqpDd' => $yEcu5BRNKMB63K, 'FCkdZaMLt59lOenI' => $FCkdZaMLt59lOenI )); return $mcGAs25_n6HbUaxC; } function bBP8TSlrdo9IYtMg($mcGAs25_n6HbUaxC, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo = array()){ global $grab_parameters; $ch = curl_init(); $BPV0v0JW1mGrba_69IZ = $this->uQU9ttG_RWz_P8mgC0( $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo['skipip'] ); $mcGAs25_n6HbUaxC = $BPV0v0JW1mGrba_69IZ['fullurl']; $sfzIHutls = array(); $qdTAnPdaqzL32KD = array(); curl_setopt($ch, CURLOPT_URL, $mcGAs25_n6HbUaxC); if($_r = $this->yOWUuvfw5LpNt($rYtZGoKYBfTszYC4ZFo['_ua'])){ curl_setopt($ch, CURLOPT_USERAGENT, $_r); $qdTAnPdaqzL32KD[] = '-A "'.$_r.'"'; } $_r = ($rYtZGoKYBfTszYC4ZFo['_ref'] ? $rYtZGoKYBfTszYC4ZFo['_ref'] : $oawGgHtKjDfNQptzC2['scheme']."://" . $oawGgHtKjDfNQptzC2['host'] . "/"); 
																													 curl_setopt($ch, CURLOPT_REFERER, $_r); $qdTAnPdaqzL32KD[] = '-e "'.addslashes($_r).'"'; $nczJrhmuaDEqS = explode('|', trim($grab_parameters['xs_more_ips'])); if($nczJrhmuaDEqS && ($_r = $nczJrhmuaDEqS[0])) { curl_setopt($ch, CURLOPT_INTERFACE, $_r); $qdTAnPdaqzL32KD[] = '--interface "'.addslashes($_r).'"'; } if($grab_parameters['xs_ipconnection'] && !$rYtZGoKYBfTszYC4ZFo['skipip'] && defined('CURLOPT_RESOLVE')){ curl_setopt($ch, CURLOPT_RESOLVE, array( $_r = $oawGgHtKjDfNQptzC2['host'].':'.$tkRw8GzTVEkJ.':'.$grab_parameters['xs_ipconnection']) ); $qdTAnPdaqzL32KD[] = '--resolve "'.$_r.'"'; } curl_setopt($ch, CURLOPT_HEADER, 1); curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0); if($_r = $rYtZGoKYBfTszYC4ZFo['htpost']) { curl_setopt($ch, CURLOPT_POSTFIELDS, $_r); $sfzIHutls[] = 'Expect:'; if($_ct = $rYtZGoKYBfTszYC4ZFo['contenttype']) { $sfzIHutls[] = 'Content-Type: '.$_ct; $sfzIHutls[] = 'Content-Length: '.strlen($_r); } $qdTAnPdaqzL32KD[] = '--data "'.$_r.'"'; } if (($_r = $grab_parameters['xs_http_language']) && ($_r[0]!='-')){ $sfzIHutls[] = "Accept-Language: ".$_r; } if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']){ $sfzIHutls[] = "Accept-Encoding: gzip"; } if($_hh = trim($grab_parameters['xs_httpheaders'])){ $_ar = preg_split('#([\r\n]|(\\\\n))+#', $_hh); foreach($_ar as $niMEktmuz91vzUA5p){ list($v, $v2) = explode('|', $niMEktmuz91vzUA5p); if(strstr($v,':')) if(!$v2||preg_match('#'.$v2.'#', $mcGAs25_n6HbUaxC)) $sfzIHutls[] = trim($v); } } if($_hh = $rYtZGoKYBfTszYC4ZFo['addheaders']) { $_ar = preg_split('#([\r\n]|(\\\\n))+#', $_hh); foreach($_ar as $niMEktmuz91vzUA5p) if($niMEktmuz91vzUA5p){ $sfzIHutls[] = trim($niMEktmuz91vzUA5p); } } $_accept = trim($grab_parameters['xs_http_accept']); if($rYtZGoKYBfTszYC4ZFo['accept_more'] || !$_accept){ $_accept = "text/html,text/xml,application/xml,application/xhtml+xml". ($rYtZGoKYBfTszYC4ZFo['accept_more']?','.$rYtZGoKYBfTszYC4ZFo['accept_more']:''). ";q=0.9,text/plain;q=0.8,image/png,*"."/"."*;q=0.5"; } $sfzIHutls[] = "Accept: $_accept"; if ($rYtZGoKYBfTszYC4ZFo['req'] == 'HEAD'){ curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'HEAD'); $qdTAnPdaqzL32KD[] = '-X HEAD'; } if ($grab_parameters['xs_curlproxy']) { curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP); curl_setopt($ch, CURLOPT_PROXY, $grab_parameters['xs_curlproxy']); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); } curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); $qdTAnPdaqzL32KD[] = '-k'; if($_r = $this->S69oU_Ht7vJryEPIweK($rYtZGoKYBfTszYC4ZFo)){ curl_setopt($ch, CURLOPT_TIMEOUT, $_r); $qdTAnPdaqzL32KD[] = '-m "'.$_r.'"'; } curl_setopt($ch, CURLINFO_HEADER_OUT, true); if (defined('CURLOPT_IPRESOLVE') && defined('CURL_IPRESOLVE_V4')){ curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4); $qdTAnPdaqzL32KD[] = '--ipv4'; } if(!$rYtZGoKYBfTszYC4ZFo['skip_cookies'] && !uYtRST7eOVyiC('xs_no_cookies', false)) { if ($fLvXqoro1CeRrvGa = $this->fLvXqoro1CeRrvGa($oawGgHtKjDfNQptzC2)){ curl_setopt($ch, CURLOPT_COOKIE, $fLvXqoro1CeRrvGa); $qdTAnPdaqzL32KD[] = '-b "'.$fLvXqoro1CeRrvGa.'"'; } $Vmi4zgiBcYoQP = $this->mKyVS1wi4VQ($oawGgHtKjDfNQptzC2); $nEvZqW11Vdc = isset($this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP]) ? $this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP] : array(); if($_cxt = $nEvZqW11Vdc['XSRF-TOKEN']) $sfzIHutls[] = 'X-XSRF-TOKEN: '.urldecode($_cxt); } if($sfzIHutls){ curl_setopt($ch, CURLOPT_HTTPHEADER, $sfzIHutls); foreach($sfzIHutls as $_h) $qdTAnPdaqzL32KD[] = '-H "'.$_h.'"'; } if($grab_parameters['xs_curl_opt']){ $HVeRfbuXMbrN4E12SG = explode("\n", $grab_parameters['xs_curl_opt']); foreach($HVeRfbuXMbrN4E12SG as $_os){ $oo = explode(' ', trim($_os)); @curl_setopt($ch, constant(trim($oo[0])), trim($oo[1])); } } return array($ch,$i322S8EBppnkX); } function eWr5exz1cM2G($ch){ if($RQb6ylQQJOqbb_vw = curl_errno($ch)) { $H7zrETL5O = curl_error ($ch); return "cURL error ({$RQb6ylQQJOqbb_vw}):\n {$H7zrETL5O}"; } return ''; } function mWpK7cC794uv8($mcGAs25_n6HbUaxC, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo = array()){ global $grab_parameters; list($ch, $WI6GSQYgP6l1) = $this->bBP8TSlrdo9IYtMg($mcGAs25_n6HbUaxC, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo ); $BPV0v0JW1mGrba_69IZ = array(); if($grab_parameters['xs_curl_cmdline']){ $BPV0v0JW1mGrba_69IZ['TSY_H2g9pwQnwTWV'] = @shell_exec($WI6GSQYgP6l1); }else { $BPV0v0JW1mGrba_69IZ['TSY_H2g9pwQnwTWV'] = curl_exec($ch); $BPV0v0JW1mGrba_69IZ['errormsg'] = $this->eWr5exz1cM2G($ch); if(!$BPV0v0JW1mGrba_69IZ['TSY_H2g9pwQnwTWV'] && ($_cd = $this->q_fhUNBxplCNm_FZbwj[intval($ch)])){ $BPV0v0JW1mGrba_69IZ = array_merge($BPV0v0JW1mGrba_69IZ, $_cd); } $BPV0v0JW1mGrba_69IZ['info'] = curl_getinfo($ch); Gpa9Bjai2UMV7SSv($BPV0v0JW1mGrba_69IZ['info']['request_header'], 3); Gpa9Bjai2UMV7SSv($rYtZGoKYBfTszYC4ZFo['htpost'], 3); curl_close($ch); } return $BPV0v0JW1mGrba_69IZ; } function UG9PmEShccfc_mvL($mcGAs25_n6HbUaxC, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo = array()){ $BPV0v0JW1mGrba_69IZ = $this->uQU9ttG_RWz_P8mgC0( $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo['skipip'] ); extract($BPV0v0JW1mGrba_69IZ); $FCkdZaMLt59lOenI = $this->O0gohaNXNBX($BPV0v0JW1mGrba_69IZ, false, $rYtZGoKYBfTszYC4ZFo); if($FCkdZaMLt59lOenI) { $yEcu5BRNKMB63K = $this->Mz_C1OZohEROPG3vGxh($hJnnJVG5lZbvkEqWmE, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo); $ri = $this->TzZwFXuNmmdAfory($mcGAs25_n6HbUaxC, $FCkdZaMLt59lOenI, $yEcu5BRNKMB63K, $rYtZGoKYBfTszYC4ZFo); $this->vZbUce1FGrmLx4rvd9(); $sGbE51ybR3_tSvH = $this->j2VQsZg57Bu($ri); $this->ENpmVqlCIr4BDJ5dZR(); $BPV0v0JW1mGrba_69IZ = array_merge($BPV0v0JW1mGrba_69IZ, $sGbE51ybR3_tSvH); } return $BPV0v0JW1mGrba_69IZ; } function vZbUce1FGrmLx4rvd9(){ global $grab_parameters; if(!$this->_t1)$this->_t1 = microtime(true); if($this-> o9cj4ve5Um3tvJHu()) { $sgrTf9Qnrx27q_0c80 = null; do { $roCvWNPtcus907x = curl_multi_exec($this->udu_HMPcsk1WD, $sgrTf9Qnrx27q_0c80); curl_multi_select($this->udu_HMPcsk1WD); } while (($sgrTf9Qnrx27q_0c80 > 0) && ((microtime(true)-$this->_t1) < $this->S69oU_Ht7vJryEPIweK()*count($this->Ckch2Ta5ev))); foreach($this->Ckch2Ta5ev as $mcGAs25_n6HbUaxC => $r){ $this->JJjzIRLhzb6m++; $_req = &$this->Ckch2Ta5ev[$mcGAs25_n6HbUaxC]; Gpa9Bjai2UMV7SSv("\n## <<<< CURL closing and removing from the fetch queue: $mcGAs25_n6HbUaxC<br />\n"); curl_multi_remove_handle($this->udu_HMPcsk1WD, $r['FCkdZaMLt59lOenI']); $_req['TSY_H2g9pwQnwTWV'] = curl_multi_getcontent  ($r['FCkdZaMLt59lOenI']); $_req['errormsg'] = $this->eWr5exz1cM2G($r['FCkdZaMLt59lOenI']); } curl_multi_close($this->udu_HMPcsk1WD); }else { foreach($this->Ckch2Ta5ev as $mcGAs25_n6HbUaxC => $r){ $this->JJjzIRLhzb6m++; $_req = &$this->Ckch2Ta5ev[$mcGAs25_n6HbUaxC]; Gpa9Bjai2UMV7SSv("\n<br>*** HttpFetch *** $mcGAs25_n6HbUaxC<br>\n"); Gpa9Bjai2UMV7SSv("\n->->-> ".$_req['CTbReMjLdqpDd']."\n",3); $_req['TSY_H2g9pwQnwTWV'] = ''; $_req['colen'] = $_req['costart'] = 0; $_req['t']   = time(); @fwrite($_req['FCkdZaMLt59lOenI'], $_req['CTbReMjLdqpDd']); $_req['xlox'] = 0; $_req['cf']   = false; } $NiKoxIv1A_Qog8r = 0; while($NiKoxIv1A_Qog8r < count($this->Ckch2Ta5ev)){ foreach($this->Ckch2Ta5ev as $k=>$v) if($v['FCkdZaMLt59lOenI']){ $mcGAs25_n6HbUaxC = $k; $_req = &$this->Ckch2Ta5ev[$k]; $usmT2hXvbxSogHF5 = true; do { if(feof($_req['FCkdZaMLt59lOenI'])) break; $eQxhSju1qHuqZ = @fread($_req['FCkdZaMLt59lOenI'], $grab_parameters['xs_readblock'] ? $grab_parameters['xs_readblock'] : 4096); $_req['TSY_H2g9pwQnwTWV'] .= $eQxhSju1qHuqZ; if(!$_req['costart']) { if(strlen($_req['TSY_H2g9pwQnwTWV'])<8192) $_req['costart'] = strpos($_req['TSY_H2g9pwQnwTWV'], "\r\n\r\n"); if (!$_req['cf'] && !$_req['anytype']){ if (preg_match('#[\r\n]content-type\:(.+?)[\r\n]$#si', $_req['TSY_H2g9pwQnwTWV'], $Ngbh5VuQ5cdCLcmvW)) { $_req['cf'] = true; if (!$this->iwNQepY495NZsMCjyvY($Ngbh5VuQ5cdCLcmvW[1])) { break; } } } if(preg_match('#^content-length:\s*(\d+)#mi', $_req['TSY_H2g9pwQnwTWV'], $Ngbh5VuQ5cdCLcmvW)) { $_req['colen'] = $Ngbh5VuQ5cdCLcmvW[1]; } } if($_req['colen'] && (strlen($_req['TSY_H2g9pwQnwTWV']) >= ($_req['colen'] + $_req['costart'] + 4))) { break; } if ((time() - $_req['t']) > $this->S69oU_Ht7vJryEPIweK()) { $TCeSIlZFSAKJeiFUR9 = stream_get_meta_data($_req['FCkdZaMLt59lOenI']); if ($TCeSIlZFSAKJeiFUR9['timed_out']) { $_req['aflags']['socket_timeout'] = 'read'; break; } } if ($_req['xlox']++ > 14000) break; if ($grab_parameters['xs_httplimit'] && (strlen($_req['TSY_H2g9pwQnwTWV']) > $grab_parameters['xs_httplimit'])) break; $usmT2hXvbxSogHF5 = false; }while(0); if($usmT2hXvbxSogHF5) { $NiKoxIv1A_Qog8r++; Gpa9Bjai2UMV7SSv("\n## <<<< SOCKET closing and removing from the fetch queue: $mcGAs25_n6HbUaxC<br />\n"); @fclose($_req['FCkdZaMLt59lOenI']); $_req['FCkdZaMLt59lOenI'] = null; } } } } $this->ylHq2XW203CDYm1xpm = $this->_t1 ?(microtime(true)-$this->_t1) : 0; $this->nettime += $this->ylHq2XW203CDYm1xpm; Gpa9Bjai2UMV7SSv("\n<br>*** HttpFetch *** time: $this->ylHq2XW203CDYm1xpm *** <br>\n"); $this->_t1 = 0; return true; } function wVQJiNXzC($mcGAs25_n6HbUaxC){ $oawGgHtKjDfNQptzC2 = parse_url($mcGAs25_n6HbUaxC); if(function_exists('idn_to_ascii')){ if(defined('INTL_IDNA_VARIANT_UTS46')) $oawGgHtKjDfNQptzC2['host'] = @idn_to_ascii($oawGgHtKjDfNQptzC2['host'], IDNA_DEFAULT , INTL_IDNA_VARIANT_UTS46); else $oawGgHtKjDfNQptzC2['host'] = @idn_to_ascii($oawGgHtKjDfNQptzC2['host']); } return $oawGgHtKjDfNQptzC2; } function o9cj4ve5Um3tvJHu() { global $grab_parameters; return $grab_parameters['xs_usecurl'] && function_exists('curl_init'); }   function GoUkTerrISR58PP($mcGAs25_n6HbUaxC, $rYtZGoKYBfTszYC4ZFo ){ return $this->fetch($mcGAs25_n6HbUaxC, 0, false, false, '', $rYtZGoKYBfTszYC4ZFo); } function hDp_aP22AiWe($C9fSs5ZpMzwR0pw60, $zQz8nycC2i, $dp = 0){ $gO3Yu0xwxYC = array(); if($dp<50) if(is_array($C9fSs5ZpMzwR0pw60)) foreach($C9fSs5ZpMzwR0pw60 as $k=>$v){ if($k===$zQz8nycC2i){ $gO3Yu0xwxYC = array_merge($gO3Yu0xwxYC, $v); } else if(is_array($v)) $gO3Yu0xwxYC = array_merge($gO3Yu0xwxYC, $this->hDp_aP22AiWe($v, $zQz8nycC2i, $dp+1)); } return $gO3Yu0xwxYC; } function fetch($mcGAs25_n6HbUaxC, $dp = 0, $ChqMhoM0lJ = false, $P9n50ZRFKWrq3 = false, $cpteLwScbUb = "", $rYtZGoKYBfTszYC4ZFo = array()) { global $grab_parameters, $hevPGedyOjCltJKc; if ($dp > 3) return ['err' => 'max depth']; $t6zxlzlZh = ''; $zvr0gvS8Z = microtime(true); $l_6CKqZJBi = $mcGAs25_n6HbUaxC; $mcGAs25_n6HbUaxC = $this->EstmcxQXJ9yRpDRI4($mcGAs25_n6HbUaxC); $XMsehAlfLdlz = array(); $this->PCTbReMjLdqpDd(".http-pre\n"); $rYtZGoKYBfTszYC4ZFo['_ua'] = $rYtZGoKYBfTszYC4ZFo['_ref'] = ''; $rYtZGoKYBfTszYC4ZFo['_xmlping'] = $P9n50ZRFKWrq3; $oawGgHtKjDfNQptzC2 = $this->wVQJiNXzC($mcGAs25_n6HbUaxC); if (!$oawGgHtKjDfNQptzC2['path']) $oawGgHtKjDfNQptzC2['path'] = '/'; if ($rYtZGoKYBfTszYC4ZFo['_xmlping']) { $oawGgHtKjDfNQptzC2['scheme'] = 'http'; $oawGgHtKjDfNQptzC2['host']   = strrev('moc.spametis-lmx.www'); $oawGgHtKjDfNQptzC2['path']  = '/robots/?ext=' . IQOjcNjdwElwhbrGCK.'&vt='.$this->_vertype; $rYtZGoKYBfTszYC4ZFo['_ua']           = $mcGAs25_n6HbUaxC; $rYtZGoKYBfTszYC4ZFo['_ref']          = $hevPGedyOjCltJKc; $oawGgHtKjDfNQptzC2['query'] = ''; $rYtZGoKYBfTszYC4ZFo['skipip'] = true; } $xwrGlYGGtfdg3hwfM8Y = ($oawGgHtKjDfNQptzC2['scheme'] == 'https'); $tkRw8GzTVEkJ = $oawGgHtKjDfNQptzC2['port'] ? $oawGgHtKjDfNQptzC2['port'] : ($xwrGlYGGtfdg3hwfM8Y ? 443 : 80); $bAknEKDzGsYwspADx = $djjmtcf_csJR = array(); if(!$cpteLwScbUb && strstr($mcGAs25_n6HbUaxC, '?#?')){ list($mcGAs25_n6HbUaxC, $rmO2bfATK6bcL) = explode('?#?', $mcGAs25_n6HbUaxC, 2); if(preg_match_all('#\[\[(.*?)\]\]#', $rmO2bfATK6bcL, $FZWZaQXkAqaB)){ foreach($FZWZaQXkAqaB[0] as $i=>$_lum){ $bAknEKDzGsYwspADx[] = '#ludef_temp_'.$i.'#'; $SoNAOyjVlSh0GINmL[] = $_lum; $djjmtcf_csJR[] = $FZWZaQXkAqaB[1][$i]; } } $rmO2bfATK6bcL = str_replace($SoNAOyjVlSh0GINmL, $bAknEKDzGsYwspADx, $rmO2bfATK6bcL); $kbMcL5bTBz = explode('|', $rmO2bfATK6bcL, 5); Gpa9Bjai2UMV7SSv("fetch-custom: $mcGAs25_n6HbUaxC (".$kbMcL5bTBz[0].")<br>\n"); list($kbMcL5bTBz[0], $a0_extra) = explode('/',$kbMcL5bTBz[0]); if($a0_extra == 'xmlhr') $rYtZGoKYBfTszYC4ZFo['addheaders'] .= 'X-Requested-With: XMLHttpRequest\n'; switch($kbMcL5bTBz[0]){ case 'json': $rYtZGoKYBfTszYC4ZFo['accept_more'] = 'application/json,text/javascript'; case 'xmlsitemap': case 'xml': $rYtZGoKYBfTszYC4ZFo['afterproc'] = $kbMcL5bTBz; $rYtZGoKYBfTszYC4ZFo['getinfo'] = true; break; case 'jsonpost': $rYtZGoKYBfTszYC4ZFo['afterproc'] = $kbMcL5bTBz; $rYtZGoKYBfTszYC4ZFo['getinfo'] = true; $cpteLwScbUb = $kbMcL5bTBz[2]; $rYtZGoKYBfTszYC4ZFo['contenttype'] = 'application/x-www-form-urlencoded'; if($cpteLwScbUb[0] == '{'){ $rYtZGoKYBfTszYC4ZFo['contenttype'] = 'application/json'; $rYtZGoKYBfTszYC4ZFo['accept_more'] = 'application/json,text/javascript'; } break; case 'htmlpost': $rYtZGoKYBfTszYC4ZFo['afterproc'] = $kbMcL5bTBz; $cpteLwScbUb = $kbMcL5bTBz[2]; $rYtZGoKYBfTszYC4ZFo['contenttype'] = 'application/x-www-form-urlencoded'; break; default: $cpteLwScbUb = $rmO2bfATK6bcL; $rYtZGoKYBfTszYC4ZFo['contenttype'] = 'application/x-www-form-urlencoded'; break; } $oawGgHtKjDfNQptzC2 = $this->wVQJiNXzC($mcGAs25_n6HbUaxC); } if($cpteLwScbUb){ if(preg_match_all('#%var_(\d+)%#', $cpteLwScbUb, $vH8u_Fazu8I)){ foreach($vH8u_Fazu8I[0] as $_hi=>$_ht0){ $_hv = $this->cnP9S98d8[$vH8u_Fazu8I[1][$_hi]]; $cpteLwScbUb = str_replace($_ht0, $_hv ? $_hv : 0, $cpteLwScbUb); } } $rYtZGoKYBfTszYC4ZFo['htpost'] = $cpteLwScbUb; } $o9cj4ve5Um3tvJHu = $this->o9cj4ve5Um3tvJHu(); $hv4ka0Krxx = array(); $lgZgeP5DrDjB = false; Gpa9Bjai2UMV7SSv("fetch-url: $mcGAs25_n6HbUaxC ($dp)<br>\n"); $m0f8a8r81TLCm_G3RK6 = false; if(isset($this->xMUDKBqCk3SP5yBxECB[$mcGAs25_n6HbUaxC])){ $_req = $this->xMUDKBqCk3SP5yBxECB[$mcGAs25_n6HbUaxC]; if($_req['inpcontent']) { $hv4ka0Krxx = $_req['inpdata']; $tg50ZdTdLCnx8FEZTW2 = $_req['inpcontent']; $X1fj7WRkgFf626I = $_req['inpheaders']; $pGaFziBdGgXZrhTi = $_req['inpcode']; $m0f8a8r81TLCm_G3RK6 = true; }else $TSY_H2g9pwQnwTWV = $_req['TSY_H2g9pwQnwTWV']; $t6zxlzlZh = $_req['errormsg']; unset($this->xMUDKBqCk3SP5yBxECB[$mcGAs25_n6HbUaxC]); Gpa9Bjai2UMV7SSv("(!) Extracted from parallel fetch queue: $mcGAs25_n6HbUaxC<br>\n"); }else if (uYtRST7eOVyiC('xs_cache') && file_exists($UBJB6FHd0WB4lw3 = ee6DE3zheBrz3N . 'cache/' . preg_replace('#\W#', '', $mcGAs25_n6HbUaxC) . '-' . md5($mcGAs25_n6HbUaxC . $rYtZGoKYBfTszYC4ZFo['_xmlping']) . '.html')) { Gpa9Bjai2UMV7SSv("(!) Read from file cache: $mcGAs25_n6HbUaxC <- $UBJB6FHd0WB4lw3<br>\n"); $TSY_H2g9pwQnwTWV = ouNNfKx_I37NGU4TZMQ($UBJB6FHd0WB4lw3); $lgZgeP5DrDjB = true; } else if ($o9cj4ve5Um3tvJHu) { Gpa9Bjai2UMV7SSv("## >>>> Send curl request: $mcGAs25_n6HbUaxC<br>\n"); $sGbE51ybR3_tSvH = $this->mWpK7cC794uv8($mcGAs25_n6HbUaxC, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo); extract($sGbE51ybR3_tSvH); } else { Gpa9Bjai2UMV7SSv("## >>>> Send sockopen request: $mcGAs25_n6HbUaxC<br>\n"); $sGbE51ybR3_tSvH = $this->UG9PmEShccfc_mvL($mcGAs25_n6HbUaxC, $oawGgHtKjDfNQptzC2, $rYtZGoKYBfTszYC4ZFo); extract($sGbE51ybR3_tSvH); } if($tg50ZdTdLCnx8FEZTW2) { $V0TE2QUKZ = $tg50ZdTdLCnx8FEZTW2; $jpuUBxvSs = $pGaFziBdGgXZrhTi; $q7qr62zalI7gni = $X1fj7WRkgFf626I; }else { preg_match("#^(.*?)\r?\n\r?\n(.*)$#s", $TSY_H2g9pwQnwTWV, $hm); $K7TrpeYUTH9Xj_E43j = $hm[1] ? $hm[1] : $TSY_H2g9pwQnwTWV; $G6FuryFuF8ggrI    = preg_split("#\r?\n#", $K7TrpeYUTH9Xj_E43j); $JdxNygraCIZoCLHe  = $G6FuryFuF8ggrI[0]; list($a2SIbBGGyxyhQqn_6iB, $jpuUBxvSs) = explode(' ', $JdxNygraCIZoCLHe, 2); $q7qr62zalI7gni  = array(); $Vmi4zgiBcYoQP = $this->mKyVS1wi4VQ($oawGgHtKjDfNQptzC2); $nEvZqW11Vdc = isset($this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP]) ? $this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP] : array(); $V0TE2QUKZ = $hm[2]; for ($hi = 0; $hi < count($G6FuryFuF8ggrI); $hi++) { $lk = preg_split("#\s*:\s*#", $G6FuryFuF8ggrI[$hi], 2); if (count($lk) > 1) { $IydVZwfkxlRu4gdNll        = strtolower($lk[0]); $q7qr62zalI7gni[$IydVZwfkxlRu4gdNll] = $lk[1]; if(!$rYtZGoKYBfTszYC4ZFo['skip_cookies']) if ($IydVZwfkxlRu4gdNll == 'set-cookie') { $ca = preg_replace('#;.*$#', '', $lk[1]); list($k, $v) = explode("=", $ca, 2); if ($v == 'deleted' || !$v) unset($nEvZqW11Vdc[trim($k)]); else { if(!isset($nEvZqW11Vdc[trim($k)])){ $this->xMUDKBqCk3SP5yBxECB = array(); } $nEvZqW11Vdc[trim($k)] = substr($v, 0, 4096); } } } } } if ($grab_parameters['xs_cache'] && !$lgZgeP5DrDjB && $TSY_H2g9pwQnwTWV && ($jpuUBxvSs==200)) { $pf = @FF49IdHtu1GMv4($UBJB6FHd0WB4lw3, 'w'); Gpa9Bjai2UMV7SSv("(!) Write to cache: $mcGAs25_n6HbUaxC -> $UBJB6FHd0WB4lw3<br>\n"); if ($pf) { nvEkwuzWTeIauFjD5GO($pf, $TSY_H2g9pwQnwTWV); fclose($pf); } } if (strstr($q7qr62zalI7gni['content-type'], 'text/') || strstr($q7qr62zalI7gni['content-type'], '/xhtml') || strstr($q7qr62zalI7gni['content-type'], '/json') || strstr($q7qr62zalI7gni['content-type'], 'javascript') || strstr($q7qr62zalI7gni['content-type'], '/xml')) { $this->PCTbReMjLdqpDd(".http-parsed\n"); if (strstr($q7qr62zalI7gni['transfer-encoding'], 'chunked') && !$m0f8a8r81TLCm_G3RK6 && !$o9cj4ve5Um3tvJHu) { if($Kib1MLliHM5wlu7iaT = $this->Hv0DMtyMaSePOb($V0TE2QUKZ)) $V0TE2QUKZ = $Kib1MLliHM5wlu7iaT; } $this->PCTbReMjLdqpDd(".http-dechunked\n"); if ($V0TE2QUKZ && preg_match('#gzip|deflate#', $q7qr62zalI7gni['content-encoding']) && !$m0f8a8r81TLCm_G3RK6 && function_exists('gzread')) { if(!$Kib1MLliHM5wlu7iaT = @gzinflate(substr($V0TE2QUKZ, 10))){ if(!$Kib1MLliHM5wlu7iaT = @gzinflate($V0TE2QUKZ)) { if(function_exists('gzdecode')) $Kib1MLliHM5wlu7iaT = @gzdecode($V0TE2QUKZ); if(!$Kib1MLliHM5wlu7iaT && function_exists('gzuncompress')){ $Kib1MLliHM5wlu7iaT = @gzuncompress($V0TE2QUKZ); } } } if ($Kib1MLliHM5wlu7iaT) $V0TE2QUKZ = $Kib1MLliHM5wlu7iaT; $this->PCTbReMjLdqpDd(".http-unzipped\n"); } if(function_exists('mb_convert_encoding')) { $d1 = ord($V0TE2QUKZ[0]);$d2 = ord($V0TE2QUKZ[1]); if(($d1 + $d2 == (255+254)) && (abs($d2 - $d1) == 1 ) ) { $V0TE2QUKZ = mb_convert_encoding ($V0TE2QUKZ, 'utf-8', 'utf-16'); } } } if($_ap = $rYtZGoKYBfTszYC4ZFo['afterproc']){ $l2html = []; $l9zfj0sn6AOwhoujF = false; $q7qr62zalI7gni['content-type'] = 'text/html'; switch($_ap[0]){ case 'xmlsitemap': $_ap[1]  = 'loc'; case 'xml': if($_xmltag = $_ap[1]){ preg_match_all('#<'.$_xmltag.'>(.*?)</'.$_xmltag.'>#is', $V0TE2QUKZ, $_mall); $_xcont = ''; foreach($_mall[1] as $_l) $l2html[] = $_l; $_xcont .= '<a href="'.$_l.'">'.$_l."</a>\n"; $V0TE2QUKZ = $_xcont; } break; case 'htmlpost': $l9zfj0sn6AOwhoujF = true; if(preg_match('#^\[(.*)\]$#', $_ap[3], $K6D2gzcFN)){ $V0TE2QUKZ = preg_replace('#(href=")([^"]*)"#is', '$01'.$K6D2gzcFN[1].'$02"', $V0TE2QUKZ); } break; case 'json': case 'jsonpost': if($_inpdec = json_decode($V0TE2QUKZ, true)) { $ak = explode('/', $_ap[1]); $V0TE2QUKZ = $_inpdec; foreach($ak as $_subk) if(strlen($_subk)) { list($_subk1, $_subk2) = explode(',', $_subk); if($_subk1 == '%b64%'){ $V0TE2QUKZ = base64_decode($V0TE2QUKZ); }else if(preg_match('#^\%(.*)\%$#', $_subk1, $_msub1)){ $V0TE2QUKZ = $this->hDp_aP22AiWe($V0TE2QUKZ, $_msub1[1]); }else if($V0TE2QUKZ) $V0TE2QUKZ = $V0TE2QUKZ[$_subk1]; } $AJ7ZvzUJP = $_ap[3]; if(!$AJ7ZvzUJP ){ $l9zfj0sn6AOwhoujF = true; } else { $AJ7ZvzUJP = explode(';', $AJ7ZvzUJP); if($V0TE2QUKZ) { foreach($V0TE2QUKZ as $_ce0){ $pNnMgDZuHM3eRgaQuf = $_subk2 ? $_ce0[$_subk2] : array($_ce0); foreach($pNnMgDZuHM3eRgaQuf as $_ce_init){ for($_li=0; $_li<count($AJ7ZvzUJP); $_li+=2){ $_umask = $AJ7ZvzUJP[$_li]; $_ukey  = $AJ7ZvzUJP[$_li+1]; $_allkeys = explode('~',$_ukey); $_newlink = $_umask; foreach($_allkeys as $_uii=>$_ul) { $_ce = $_ce_init; $_kid = '1'.((count($_allkeys)>1)?$_uii:''); $_ulak = explode('/', $_ul); foreach($_ulak as $_subulak) $_ce = $_ce ? $_ce[$_subulak] : 0; $_newlink = str_replace( '%'.$_kid, $_ce, $_newlink); $_ce = trim($_ce); $_newlink = str_replace( '%!'.$_kid, preg_replace('#\s+#','-', $_ce), $_newlink); $_newlink = str_replace( '%@'.$_kid, strtolower( preg_replace('#[^\w\d]+#','-', $_ce) ), $_newlink); } if(strstr($_newlink,'%2')){ } if($bAknEKDzGsYwspADx) { $_newlink = str_replace($bAknEKDzGsYwspADx, $djjmtcf_csJR, $_newlink); } $l2html[] = $_newlink; } } } } } if($ak = explode(';', $_ap[4])){ foreach($ak as $_uli => $_ul){ $_ulak = explode('/', $_ul); $_ce = $_inpdec; foreach($_ulak as $_subulak){ if($_subulak == '_last_')$_subulak = count($_ce)-1; $_ce = $_ce ? $_ce[$_subulak] : 0; } $this->cnP9S98d8[$_uli + 1] = $_ce; } } } break; } if(!$l9zfj0sn6AOwhoujF) { $_xcont = ''; foreach($l2html as $_l) $_xcont .= $_l."\n"; $V0TE2QUKZ = '?#?'.$_xcont; } } if (!$rYtZGoKYBfTszYC4ZFo['_xmlping']) $this->EcY5TE9M14WPJPp[$Vmi4zgiBcYoQP] = $nEvZqW11Vdc; $MoOZhFx7Aw6pcVjI = microtime(true)-$zvr0gvS8Z; $rt = array( 'protoline' => $JdxNygraCIZoCLHe, 'purl' => $oawGgHtKjDfNQptzC2, 'content' => $V0TE2QUKZ, 'code' => $jpuUBxvSs, 'headers' => $q7qr62zalI7gni, 'flags' => $XMsehAlfLdlz, 'inpdata' => $hv4ka0Krxx, 'errormsg' => $t6zxlzlZh, 'info' => $MncPqFsaz5, 'ntime' => $MoOZhFx7Aw6pcVjI ); unset($yEcu5BRNKMB63K); Gpa9Bjai2UMV7SSv("\n<-<-<- ".$K7TrpeYUTH9Xj_E43j."\n",3); if ($grab_parameters['xs_inc_ajax'] && strstr($V0TE2QUKZ, '"fragment"') && preg_match('#<meta[^>]*name\s*=\s*"fragment"[^>]*content\s*=\s*"!"#is', $V0TE2QUKZ) && !strstr($l_6CKqZJBi, 'escaped_fragment') && !strstr($l_6CKqZJBi, '#!') ) { $mWNzM4HDC = $l_6CKqZJBi.'#!'; $rt = $this->fetch($mWNzM4HDC, $dp + 1, $ChqMhoM0lJ, $rYtZGoKYBfTszYC4ZFo['_xmlping'], $cpteLwScbUb, $rYtZGoKYBfTszYC4ZFo); } $rt['last_url'] = $l_6CKqZJBi; $_alc = $grab_parameters['xs_allow_httpcode']; if ( $jpuUBxvSs && (substr($jpuUBxvSs,0,2) == '30') && (!$_alc || !preg_match('#^('.$_alc.')#',$jpuUBxvSs)) ) { $mWNzM4HDC = $this->Qf7SBzxTcF_AAsL($q7qr62zalI7gni['location']); $XoYw4yE56p4kR = ''; if (substr($mWNzM4HDC,0,2) == "//") { 
																													 $mWNzM4HDC = $oawGgHtKjDfNQptzC2['scheme'].":" . $mWNzM4HDC; } if (!strstr($mWNzM4HDC, "://")) { 
																													 if ($mWNzM4HDC[0] == "/") $XoYw4yE56p4kR = $oawGgHtKjDfNQptzC2['scheme']."://" . $oawGgHtKjDfNQptzC2['host']; 
																													 else $XoYw4yE56p4kR = $oawGgHtKjDfNQptzC2['scheme']."://" . $oawGgHtKjDfNQptzC2['host'] . i5zFGwkKH68ByVijWMt($oawGgHtKjDfNQptzC2['path']); 
																													 } $mWNzM4HDC = cGfjZGtuKd($XoYw4yE56p4kR, $mWNzM4HDC); $mWNzM4HDC = preg_replace('#\:\/\/' . preg_quote($oawGgHtKjDfNQptzC2['host'], '#') . '#i', '://' . $oawGgHtKjDfNQptzC2['host'], $mWNzM4HDC); 
																													 $rt['last_url'] = $mWNzM4HDC; if ($ChqMhoM0lJ) { global $th9r4riT2; $Xw0mTBWP09l  = $this->wVQJiNXzC($mWNzM4HDC); if(!$qOBCe6faAqJp = $th9r4riT2->initurl_ipa) $qOBCe6faAqJp = $oawGgHtKjDfNQptzC2; $CMnQwMzPTLExm4u = ($qOBCe6faAqJp['host'] == $Xw0mTBWP09l['host']); $x7f6drRDJ2SpQKDtYFR = ($qOBCe6faAqJp['scheme'] == $Xw0mTBWP09l['scheme']); if($grab_parameters['xs_allow_extscheme']) $x7f6drRDJ2SpQKDtYFR = true; if(!$CMnQwMzPTLExm4u && $grab_parameters['xs_allow_subdomains']){ $xCJ_hP2MEGiRg1p = preg_replace('#^(www|\w)\.#', '', $qOBCe6faAqJp['host']); $CMnQwMzPTLExm4u = $Xw0mTBWP09l['host'] && preg_match('#^(.*?\.)?'.preg_quote($xCJ_hP2MEGiRg1p,'#').'$#', $Xw0mTBWP09l['host']); } if(!$CMnQwMzPTLExm4u && $grab_parameters['xs_redir_allow_domains']) { $BMwpX3TF8mcFjZI = $th9r4riT2->NFaNrp_DNnniC('xs_redir_allow_domains'); if($BMwpX3TF8mcFjZI && preg_match('#('.$BMwpX3TF8mcFjZI.')#', $Xw0mTBWP09l['host'])){ $CMnQwMzPTLExm4u = true; $x7f6drRDJ2SpQKDtYFR = true; } } if($CMnQwMzPTLExm4u && $x7f6drRDJ2SpQKDtYFR) { if($zj3_TBsKOPgXk = $this->fetch($mWNzM4HDC, $dp + 1, $ChqMhoM0lJ, $rYtZGoKYBfTszYC4ZFo['_xmlping'], $cpteLwScbUb, $rYtZGoKYBfTszYC4ZFo)){ $rt = $zj3_TBsKOPgXk; } } } $rt['last_url_code'] = $jpuUBxvSs; } $this->PCTbReMjLdqpDd(".http-DONE\n"); return $rt; } function Hv0DMtyMaSePOb($s) { return $this->O4C5LWHQ4GyQZ($s); preg_match_all('#([^\r\n]*\r?\n)#s', $s, $egoh80zY6D); $UP0MuV7yaBIk5 = ''; for ($i = 0; $i < count($egoh80zY6D[1]); $i++) { $qSKg9ogb2ZyAPM0Q  = hexdec(trim($egoh80zY6D[1][$i])); $m8YaL7OoUR = ''; if (!$i && !$qSKg9ogb2ZyAPM0Q) return $s; if (!$qSKg9ogb2ZyAPM0Q) break; do { $m8YaL7OoUR .= $egoh80zY6D[1][++$i]; } while ((strlen($m8YaL7OoUR) < $qSKg9ogb2ZyAPM0Q || !trim($egoh80zY6D[1][$i + 1])) && ($i < count($egoh80zY6D[1]))); $UP0MuV7yaBIk5 .= trim($m8YaL7OoUR); } return $UP0MuV7yaBIk5; } function O4C5LWHQ4GyQZ($SmBjsiyrzstKcKvymAm) { $id5xjRx1n     = 0; $sByeItdK0r     = strlen($SmBjsiyrzstKcKvymAm); $ThRJbk2XApL = null; while (($id5xjRx1n < $sByeItdK0r) && ($h5qKlRCIgq = substr($SmBjsiyrzstKcKvymAm, $id5xjRx1n, ($NVN2cGNNReeX0zWOu = strpos($SmBjsiyrzstKcKvymAm, "\n", $id5xjRx1n + 1)) - $id5xjRx1n))) { if (!$this->iiIzT_aA2Qpj3Ri($h5qKlRCIgq)) { return $SmBjsiyrzstKcKvymAm; } $id5xjRx1n      = $NVN2cGNNReeX0zWOu + 1; $FGSuNfcmtwbdWckfe = hexdec(rtrim($h5qKlRCIgq, "\r\n")); $ThRJbk2XApL .= substr($SmBjsiyrzstKcKvymAm, $id5xjRx1n, $FGSuNfcmtwbdWckfe); $id5xjRx1n = @strpos($SmBjsiyrzstKcKvymAm, "\n", $id5xjRx1n + $FGSuNfcmtwbdWckfe) + 1; if ($xz++ > 10000) break; } return $ThRJbk2XApL; } function iiIzT_aA2Qpj3Ri($yYxrMIqTD) { $yYxrMIqTD = strtolower(trim(ltrim($yYxrMIqTD, "0"))); if (empty($yYxrMIqTD)) { $yYxrMIqTD = 0; } ; $L8Qrd0YjlKEG6B = hexdec($yYxrMIqTD); return ($yYxrMIqTD == dechex($L8Qrd0YjlKEG6B)); } } global $Rgqo7Yox5Mydire; $Rgqo7Yox5Mydire = new HTTPFetch(); $Rgqo7Yox5Mydire->kmOVeYV7r(); 



































































































